config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  
  resources :users, only: [:show, :index] do
    resources :friend_requests, only: [:index, :create, :update, :destroy]
  end

  resources :posts do 
    resources :comments, only: [:create]
  end
  resources :comments, only: [:update]

  resources :friendships, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'
  has_many :likes, as: :likeable

  validates :body, presence: true
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :receiver, class_name: 'User'
  belongs_to :sender, class_name: 'User'
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :friend_owner, class_name: 'User'
  belongs_to :friend, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]
  
  validates :username, presence: true, uniqueness: true

  has_many :friendships, foreign_key: :friend_owner_id
  has_many :friends, class_name: 'User', through: :friendships

  has_many :posts, foreign_key: :author_id
  has_many :comments, foreign_key: :author_id
  has_many :likes, dependent: :destroy

  has_many :friend_requests, foreign_key: :receiver_id
  has_many :senders, class_name: 'User', through: :friend_requests

  after_create :send_welcome_email


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  private

  def send_welcome_email
    UserMailer.with(user: self).welcome_email.deliver_later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :profile_pic])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Post.find(params[:post_id]).comments.build(body: params[:body], author_id: current_user.id)
    @comment.save
    redirect_to Post.find(params[:post_id])
  end

  def update
    @comment = Comment.find(params[:id])
    if params[:like]
      like = @comment.likes.create(user_id: current_user.id)
    elsif params[:dislike]
      like = @comment.likes.find_by(user_id: current_user.id)
      like.destroy
    end
    redirect_to @comment.post
  end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  def index
    @requests = FriendRequest.where(receiver_id: current_user.id, declined_accepted: false)
  end

  def create
    @request  = FriendRequest.create(sender_id: current_user.id, receiver_id: params[:user_id])
    redirect_to User.find(params[:user_id])
  end

  def update
    @request = FriendRequest.find(params[:id])
    if params[:accept]
      @request.declined_accepted = true
      Friendship.create(friend_owner_id: current_user.id, friend_id: @request.sender_id)
      Friendship.create(friend_owner_id: @request.sender_id, friend_id: current_user.id)
    else
      @request.declined_accepted = true
    end
    @request.save
    redirect_to user_friend_requests_path(current_user)
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def destroy
    @friendship1 = Friendship.find(params[:id])
    user = @friendship1.friend_id
    @friendship2 = Friendship.find_by(friend_owner_id: @friendship1.friend_id, friend_id: @friendship1.friend_owner_id)
    @f_request1 = FriendRequest.find_by(receiver_id: @friendship1.friend_id, sender_id: @friendship1.friend_owner_id)
    @f_request2 = FriendRequest.find_by(receiver_id: @friendship1.friend_owner_id, sender_id: @friendship1.friend_id)
    @friendship1.destroy
    @friendship2.destroy
    @f_request1.destroy if @f_request1
    @f_request2.destroy if @f_request2
    redirect_to user_path(user)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def create
    @post = User.find(current_user.id).posts.build(post_params)
    if @post.save
      redirect_to @post
    else
      render 'posts/new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.where(author_id: current_user.id).or(Post.where(author_id: current_user.friend_ids)).order(created_at: :desc)
  end

  def edit
    @post = Post.find(params[id])
  end

  def update
    @post = Post.find(params[:id])
    if params[:like]
      like = @post.likes.create(user_id: current_user.id)
      redirect_to @post
    elsif params[:dislike]
      like = @post.likes.find_by(user_id: current_user.id)
      like.destroy
      redirect_to @post
    elsif @post.update(post_params)
      redirect_to @post
    else
      render 'posts/edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to '/'
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = []
    if params[:searched]
      if params[:friends] == '1'
        @users = current_user.friends
      elsif !params[:username].empty?
        @users = User.where("lower(username) LIKE ? AND id != ?", "%#{params[:username]}%".downcase, current_user.id)
      end
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def friendship(user1, user2)
    Friendship.find_by(friend_owner_id: user1.id, friend_id: user2.id)
  end

  def request_sendable?(user)
    fr1 = FriendRequest.find_by(sender_id: current_user.id, receiver_id: user.id)
    fr2 = FriendRequest.find_by(sender_id: user.id, receiver_id: current_user.id)
    !user.friends.include?(current_user) && !fr1 && !fr2
  end

  def user_likes?(likeable)
    Like.find_by(likeable_type: likeable.class.to_s, likeable_id: likeable.id, user_id: current_user.id)
  end
end

app/views/friend_requests/index.html.erb
<h1>Your Friend Requests</h1>
<% if @requests.empty? %>
  <p>No requests at this time!<p>
<% else %>
  <% @requests.each do |rq| %>
  <div>
    <%= link_to User.find(rq.sender_id).username, user_path(rq.sender_id) %>
    <%= button_to 'Accept', user_friend_request_path(user_id: current_user.id, id: rq.id, accept: true), method: :put %>
    <%= button_to 'Decline', user_friend_request_path(user_id: current_user.id, id: rq.id, accept: false), method: :put %>
  </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    
    <% if user_signed_in? %>
      <div>
      Signed In As <%= link_to current_user.username, current_user %> 
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> 
      <%= link_to 'Home', posts_path %> 
      <%= link_to current_user.friend_requests.where(declined_accepted: false).empty? ? 'Friend Requests' : "Friend Requests (#{current_user.friend_requests.where(declined_accepted: false).count})", user_friend_requests_path(current_user) %>  
      <%= link_to 'Find Friends', users_path %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br />
  <%= f.label :body %>
  <%= f.text_area :body, rows: 10, cols: 60 %><br />
  <%= f.submit %>
<% end %>

app/views/posts/_post_comments.html.erb
<div>
  <% locals[:post].comments.each do |c| %>
    <div>Commenter: <%= link_to c.author.username, user_path(c.author) %></div>
    <div>Comment: <%= c.body %></div>
    <p><%= c.likes.count %> Likes - <%= link_to_if(!user_likes?(c), 'Like', comment_path(c, like: true), method: :put) { link_to 'Liked', comment_path(c, dislike: true), method: :put } %></p>

  <% end %>
</div>

app/views/posts/_posts.html.erb
<div> 
  <% locals[:posts].each do |post| %>
    <div>
      <div><%= link_to post.title, post %> By <%= link_to post.author.username, user_path(post.author) %></div>
      <div><%= post.body %></div>
      <%= render 'posts/post_comments', locals: { post: post } %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>
<%= link_to 'Back', @post %>

app/views/posts/index.html.erb
<h1>Timeline</h1>
<%= link_to 'Write Post', new_post_path %>
<%= render 'posts', locals: { posts: @posts } %>

app/views/posts/new.html.erb
<h1>Write a Post!</h1>
<%= render 'form' %>
<%= button_to 'Back to Timeline', posts_path, method: :get %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<%= link_to_if(@post.author == current_user, 'Edit', edit_post_path(@post)) { '' } %>
<div><%= @post.body %></div>
<p><%= @post.likes.count %> Likes - <%= link_to_if(!user_likes?(@post), 'Like', post_path(@post, like: true), method: :put) { link_to 'Liked', post_path(@post, dislike: true), method: :put } %></p>
<div>
  <p>Make a Comment</p>
  <%= form_with url: post_comments_url(@post), method: 'post' do |f| %>
    <%= f.text_area :body %><br />
    <%= f.submit 'Comment' %>
  <% end %>
</div>
<%= render 'post_comments', full: true, locals: { post: @post } %>

app/views/users/index.html.erb
<h1>Search Users</h1>

<%= form_with url: '/users', method: 'get', local: true do |f| %>
  <%= f.hidden_field :searched, value: true %>
  <%= f.text_field :username %>
  <%= f.check_box :friends %>
  <%= f.label 'Show all friends' %>
  <%= f.submit 'Search' %>
<% end %>

<% if params[:searched] %>
  <% if @users.empty? %>
    <p>No usernames matched.</p>
  <% else %>
    <% @users.each do |u| %>
      <p><%= link_to u.username, u %><p>
    <% end %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile</h2>

<%= image_tag @user.profile_pic, size: '80x80' %>

<% if @user != current_user %> 
  <% if current_user.friends.include?(@user) %> 
    <%= button_to 'Unfriend', friendship_path(friendship(current_user, @user)), method: :delete %>
  <% elsif request_sendable?(@user) %>
    <%= button_to 'Send Friend Request', user_friend_requests_path(@user) %> 
  <% end %>
<% elsif @user == current_user %>
  <%= button_to 'Settings', edit_user_registration_path(current_user), method: :get %>
<% end %>

<%= render 'posts/posts', locals: { posts: @user.posts } %>